FROM amazoncorretto:17-alpine-jdk
MAINTAINER velukrishna9@gmail.com
COPY target/kafka-order-producer-0.0.1-SNAPSHOT.jar kafka-order-producer-0.0.1.jar
ENTRYPOINT ["java","-jar","/kafka-order-producer-0.0.1.jar"]